# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/14751/Desktop/ov5640_fun4_lcd_up3/project_1/project_1.srcs/sources_1/ip/ila_char_horizon1/ila_char_horizon1.xci
# IP: The module: 'ila_char_horizon1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14751/Desktop/ov5640_fun4_lcd_up3/project_1/project_1.gen/sources_1/ip/ila_char_horizon1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_char_horizon1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/14751/Desktop/ov5640_fun4_lcd_up3/project_1/project_1.gen/sources_1/ip/ila_char_horizon1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_char_horizon1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/14751/Desktop/ov5640_fun4_lcd_up3/project_1/project_1.gen/sources_1/ip/ila_char_horizon1/ila_char_horizon1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_char_horizon1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/14751/Desktop/ov5640_fun4_lcd_up3/project_1/project_1.srcs/sources_1/ip/ila_char_horizon1/ila_char_horizon1.xci
# IP: The module: 'ila_char_horizon1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14751/Desktop/ov5640_fun4_lcd_up3/project_1/project_1.gen/sources_1/ip/ila_char_horizon1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_char_horizon1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/14751/Desktop/ov5640_fun4_lcd_up3/project_1/project_1.gen/sources_1/ip/ila_char_horizon1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_char_horizon1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/14751/Desktop/ov5640_fun4_lcd_up3/project_1/project_1.gen/sources_1/ip/ila_char_horizon1/ila_char_horizon1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_char_horizon1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
