# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/vivado/project_3/ov5640_fun4_lcd.srcs/constrs_1/new/pin.xdc

# IP: D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# XDC: d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# XDC: d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc
