# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "D:/vivado/project_3/project_1.runs/synth_1/ov5640_fun4_lcd.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado/project_3/project_1.cache/wt [current_project]
set_property parent.project_path D:/vivado/project_3/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/vivado/project_3/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/image_process.v
  D:/vivado/project_3/project_1.srcs/sources_1/new/judge.sv
  D:/vivado/project_3/project_1.srcs/sources_1/new/setstorehouse.sv
}
read_verilog -library xil_defaultlib {
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/Get_EigenValue.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/sobel/Sobel_Edge_Detector.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/dilation/VIP_Bit_Dilation_Detector.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/erosion/VIP_Bit_Erosion_Detector.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/projection/VIP_horizon_projection.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/projection/VIP_vertical_projection.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/add_char.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/add_grid.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/binarization/binarization.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/char_binarization.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/char_horizon_projection.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/char_vertical_projection.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/lcd_top/clk_div.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_dri/cmos_capture_data.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/ddr3_top/ddr3_fifo_ctrl.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/ddr3_top/ddr3_rw.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/ddr3_top/ddr3_top.v
  D:/vivado/project_3/project_1.srcs/sources_1/new/fpga_sevo.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_dri/i2c_dri.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_dri/i2c_ov5640_rgb565_cfg.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/lcd_top/lcd_driver.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/lcd_top/lcd_rgb_top.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/line_shift_ram_8bit.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/matrix_generate_3x3_1bit.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/matrix_generate_3x3_8bit.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_dri/ov5640_dri.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/picture_size.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/lcd_top/rd_id.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/rgb2ycbcr.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/image_process/template_matching.v
  D:/vivado/project_3/project_1.srcs/sources_1/new/vlg_cal.v
  D:/vivado/project_3/project_1.srcs/sources_1/new/vlg_echo.v
  D:/vivado/project_3/project_1.srcs/sources_1/new/vlg_en.v
  D:/vivado/project_3/project_1.srcs/sources_1/new/vlg_trig.v
  D:/vivado/project_3/project_1.srcs/sources_1/new/vlg_ultrawave.v
  D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/new/ov5640_fun4_lcd.v
}
read_ip -quiet D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/ip/projection_ram/projection_ram.xci
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/projection_ram/projection_ram_ooc.xdc]

read_ip -quiet D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/ip/rd_fifo/rd_fifo.xci
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/rd_fifo/rd_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/rd_fifo/rd_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/rd_fifo/rd_fifo_ooc.xdc]

read_ip -quiet D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/ip/wr_fifo/wr_fifo.xci
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/wr_fifo/wr_fifo.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/wr_fifo/wr_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/wr_fifo/wr_fifo_ooc.xdc]

read_ip -quiet D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/ip/cordic/cordic.xci
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/cordic/cordic_ooc.xdc]

read_ip -quiet D:/vivado/project_3/ov5640_fun4_lcd.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/vivado/project_3/ov5640_fun4_lcd.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado/project_3/ov5640_fun4_lcd.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files D:/vivado/project_3/ov5640_fun4_lcd.srcs/constrs_1/new/pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -incremental D:/vivado/project_3/project_1.srcs/utils_1/imports/synth_1/ov5640_fun4_lcd.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top ov5640_fun4_lcd -part xc7a100tfgg484-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ov5640_fun4_lcd.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ov5640_fun4_lcd_utilization_synth.rpt -pb ov5640_fun4_lcd_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
