# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/14751/Desktop/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/ip/cordic/cordic.xci
# IP: The module: 'cordic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14751/Desktop/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.gen/sources_1/ip/cordic/cordic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/14751/Desktop/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.srcs/sources_1/ip/cordic/cordic.xci
# IP: The module: 'cordic' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/14751/Desktop/ov5640_fun4_lcd_up3/project_1/ov5640_fun4_lcd.gen/sources_1/ip/cordic/cordic_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cordic'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
